In [1]:
def sudoku(problem):    
    import numpy as np
    N = [1,2,3,4,5,6,7,8,9]
    n=set(N)
    problem = np.array(problem)
    flag=True
    while problem.sum() != 405: 
        problem_copy=np.copy(problem)
        ls1=[]
        ls2=[]
        #ls2 will be the list of list of numbers (nested list) that are to be filled for each of the '9' "3 x 3" matrices.

        for i in range(9):
            for j in range(9):
                if i%3==0 and j%3==0:
                    for k in problem[i:i+3,j:j+3]:
                        for l in range(3):
                            z=k[l]
                            ls1.append(z)
                    s1=set(ls1)
                    s2=n-s1
                    ls2.append(s2)
                    if len(s2)==1:
                        problem[i:i+3,j:j+3]=np.where(problem[i:i+3,j:j+3]==0, list(s2)[0], problem[i:i+3,j:j+3])
                    ls1=[]

        for i in range(9):
            for j in range(9):
                if problem[i][j]==0:
                    s3 = set(list(problem[:,j])+list(problem[i,:]))
                    s4=n-s3
                    if len(s4)==1:
                        problem[i][j]=list(s4)[0]
                    if len(s4)!=1:
                        if i<3:
                            if j<3:
                                if len(s4 & ls2[0]) == 1:
                                    problem[i][j]=list(s4 & ls2[0])[0]

                            elif j<6:
                                if len(s4 & ls2[1]) == 1:
                                    problem[i][j]=list(s4 & ls2[1])[0]

                            elif j<9:
                                if len(s4 & ls2[2]) == 1:
                                    problem[i][j]=list(s4 & ls2[2])[0]


                        elif i<6:
                            if j<3:
                                if len(s4 & ls2[3]) == 1:
                                    problem[i][j]=list(s4 & ls2[3])[0]

                            elif j<6:
                                if len(s4 & ls2[4]) == 1:
                                    problem[i][j]=list(s4 & ls2[4])[0] 

                            elif j<9:
                                if len(s4 & ls2[5]) == 1:
                                    problem[i][j]=list(s4 & ls2[5])[0]


                        elif i<9:
                            if j<3:
                                if len(s4 & ls2[6]) == 1:
                                    problem[i][j]=list(s4 & ls2[6])[0]

                            elif j<6:
                                if len(s4 & ls2[7]) == 1:
                                    problem[i][j]=list(s4 & ls2[7])[0]

                            elif j<9:
                                if len(s4 & ls2[8]) == 1:
                                    problem[i][j]=list(s4 & ls2[8])[0]


        compare = problem_copy == problem
        equal_arrays = compare.all()
        if equal_arrays:
            print('Sorry, either the puzzle is very hard or the entry is invalid')
            flag = False
            break
    if flag:
        print("The solution for the sudoku puzzle is : ",problem)

In [2]:
#Example problem 1
problem1 = [[0, 0, 0, 2, 6, 0, 7, 0, 1],
           [6, 8, 0, 0, 7, 0, 0, 9, 0],
           [1, 9, 0, 0, 0, 4, 5, 0, 0],
           [8, 2, 0, 1, 0, 0, 0, 4, 0],
           [0, 0, 4, 6, 0, 2, 9, 0, 0],
           [0, 5, 0, 0, 0, 3, 0, 2, 8],
           [0, 0, 9, 3, 0, 0, 0, 7, 4],
           [0, 4, 0, 0, 5, 0, 0, 3, 6],
            [7, 0, 3, 0, 1, 8, 0, 0, 0]]

In [3]:
#Example problem 2
problem2 = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
           [6, 0, 0, 1, 9, 5, 0, 0, 0],
           [0, 9, 8, 0, 0, 0, 0, 6, 0],
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [4]:
sudoku(problem1)

The solution for the sudoku puzzle is :  [[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]


In [5]:
sudoku(problem2)

The solution for the sudoku puzzle is :  [[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
